"""Ensure all audit log detail columns are present

Revision ID: 4fe5a2fa0484
Revises: 93754cfc2026
Create Date: 2025-05-13 00:19:02.305074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fe5a2fa0484'
down_revision = '93754cfc2026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('encryption_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=16),
               existing_nullable=True)
        batch_op.alter_column('encryption_nonce',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('encryption_nonce',
               existing_type=sa.LargeBinary(length=12),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
        batch_op.alter_column('encryption_salt',
               existing_type=sa.LargeBinary(length=16),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
