"""Add http_version, status_code, response_size, referer to AuditLog

Revision ID: 876941880e71
Revises: e0b0419cb12c
Create Date: 2025-05-11 22:08:56.073323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '876941880e71'
down_revision = 'e0b0419cb12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referer', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('http_version', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('status_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('response_size', sa.Integer(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('encryption_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=16),
               existing_nullable=True)
        batch_op.alter_column('encryption_nonce',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('encryption_nonce',
               existing_type=sa.LargeBinary(length=12),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
        batch_op.alter_column('encryption_salt',
               existing_type=sa.LargeBinary(length=16),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('response_size')
        batch_op.drop_column('status_code')
        batch_op.drop_column('http_version')
        batch_op.drop_column('referer')

    # ### end Alembic commands ###
