"""Add encryption metadata columns to Document model

Revision ID: 9802fa5ff2a3
Revises: 
Create Date: 2025-05-11 18:44:56.687725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9802fa5ff2a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_filesize', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('encryption_salt', sa.LargeBinary(length=16), nullable=True))
        batch_op.add_column(sa.Column('encryption_nonce', sa.LargeBinary(length=12), nullable=True))
        batch_op.drop_column('encryption_key_ref')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_key_ref', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('encryption_nonce')
        batch_op.drop_column('encryption_salt')
        batch_op.drop_column('encrypted_filesize')

    # ### end Alembic commands ###
