"""Add http_version, status_code, response_size to AuditLog

Revision ID: b8ea60f5a51f
Revises: 876941880e71
Create Date: 2025-05-11 22:16:31.413775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8ea60f5a51f'
down_revision = '876941880e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('encryption_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=16),
               existing_nullable=True)
        batch_op.alter_column('encryption_nonce',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('encryption_nonce',
               existing_type=sa.LargeBinary(length=12),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
        batch_op.alter_column('encryption_salt',
               existing_type=sa.LargeBinary(length=16),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
