"""empty message

Revision ID: ce8fd857166b
Revises: 5897ed856faa
Create Date: 2025-05-11 23:05:56.310619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce8fd857166b'
down_revision = '5897ed856faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('encryption_salt',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=16),
               existing_nullable=True)
        batch_op.alter_column('encryption_nonce',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('encryption_nonce',
               existing_type=sa.LargeBinary(length=12),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)
        batch_op.alter_column('encryption_salt',
               existing_type=sa.LargeBinary(length=16),
               type_=mysql.TINYBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
